# Generated by Django 5.1.2 on 2024-10-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.CharField(max_length=255)),
                ('top_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
